# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: houmain.spright
PackageVersion: 3.5.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: spright-3.5.0-win64/spright.exe
  PortableCommandAlias: ''
InstallModes:
- silent
UpgradeBehavior: uninstallPrevious
Commands:
- spright
ReleaseDate: 2024-06-17
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/houmain/spright/releases/download/3.5.0/spright-3.5.0-win64.zip
  InstallerSha256: 5909644681DE388A6DCD7F7623CE6AB154D2B86906AA13B2085050309CB0A00E
ManifestType: installer
ManifestVersion: 1.6.0
