# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: houmain.keymapper
PackageVersion: 3.4.0
PackageLocale: en-US
Publisher: Albert Kalchmair
PackageName: keymapper
License: GPL-3.0
ShortDescription: A cross-platform context-aware key remapper
ManifestType: defaultLocale
ManifestVersion: 1.5.0
